start:
  x: 0.2
  y: 1
goal:
  x: 9.4
  y: 0
obstacles:
 - x1: 2
   y1: 1
   x2: 3
   y2: 5
 - x1: 2
   y1: 4
   x2: 7
   y2: 5
 - x1: 7.5
   y1: 0
   x2: 9
   y2: 6
 - x1: 6
   y1: 6
   x2: 8
   y2: 8
 - x1: 1
   y1: 7
   x2: 3
   y2: 9
